
Namespace(D_lr=0.0001, base_lr=0.01, batch_size=4, beta=0.3, consistency=1.0, consistency_rampup=40.0, consistency_type='kl', consistency_weight=0.1, deterministic=1, ema_decay=0.99, exp='LA/SSL_DTC_UNet3D', gamma=0.5, gpu='1', labeled_bs=2, labelnum=16, max_iterations=6000, root_path='/data/sohui/LA_dataset/2018LA_Seg_TrainingSet', seed=1337, with_cons='without_cons')
Traceback (most recent call last):
  File "/home/psh/PycharmProjects/DTC_57/code/SSL_train_la_dtc_UNet3D.py", line 142, in <module>
    model = create_model()
  File "/home/psh/PycharmProjects/DTC_57/code/SSL_train_la_dtc_UNet3D.py", line 134, in create_model
    model = unet_3D().cuda()
  File "/home/psh/anaconda3/envs/lung_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/psh/anaconda3/envs/lung_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/psh/anaconda3/envs/lung_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/psh/anaconda3/envs/lung_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/psh/anaconda3/envs/lung_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/home/psh/anaconda3/envs/lung_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/psh/anaconda3/envs/lung_unet/lib/python3.7/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available