2022-02-07 12:16:05,588 INFO    MainThread:6854 [internal.py:wandb_internal():87] W&B internal server running at pid: 6854, started at: 2022-02-07 12:16:05.587671
2022-02-07 12:16:05,597 DEBUG   HandlerThread:6854 [handler.py:handle_request():130] handle_request: check_version
2022-02-07 12:16:05,599 INFO    WriterThread:6854 [datastore.py:open_for_write():77] open: /home/sohui/code/DTC/code/wandb/run-20220207_121603-2t3o8y1h/run-2t3o8y1h.wandb
2022-02-07 12:16:05,611 DEBUG   SenderThread:6854 [sender.py:send():238] send: header
2022-02-07 12:16:05,611 DEBUG   SenderThread:6854 [sender.py:send_request():252] send_request: check_version
2022-02-07 12:16:05,711 DEBUG   SenderThread:6854 [sender.py:send():238] send: run
2022-02-07 12:16:06,001 INFO    SenderThread:6854 [dir_watcher.py:__init__():169] watching files in: /home/sohui/code/DTC/code/wandb/run-20220207_121603-2t3o8y1h/files
2022-02-07 12:16:06,001 INFO    SenderThread:6854 [sender.py:_start_run_threads():825] run started: 2t3o8y1h with start time 1644236164
2022-02-07 12:16:06,002 DEBUG   SenderThread:6854 [sender.py:send():238] send: summary
2022-02-07 12:16:06,003 INFO    SenderThread:6854 [sender.py:_save_file():960] saving file wandb-summary.json with policy end
2022-02-07 12:16:06,009 DEBUG   HandlerThread:6854 [handler.py:handle_request():130] handle_request: run_start
2022-02-07 12:16:06,023 DEBUG   HandlerThread:6854 [meta.py:__init__():40] meta init
2022-02-07 12:16:06,024 DEBUG   HandlerThread:6854 [meta.py:__init__():54] meta init done
2022-02-07 12:16:06,024 DEBUG   HandlerThread:6854 [meta.py:probe():214] probe
2022-02-07 12:16:06,044 DEBUG   HandlerThread:6854 [git.py:repo():33] git repository is invalid
2022-02-07 12:16:06,045 DEBUG   HandlerThread:6854 [meta.py:_save_pip():58] save pip
2022-02-07 12:16:06,051 DEBUG   HandlerThread:6854 [meta.py:_save_pip():72] save pip done
2022-02-07 12:16:06,052 DEBUG   HandlerThread:6854 [meta.py:_save_conda():79] save conda
2022-02-07 12:16:06,061 ERROR   HandlerThread:6854 [meta.py:_save_conda():88] Error saving conda packages
Traceback (most recent call last):
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/site-packages/wandb/sdk/internal/meta.py", line 84, in _save_conda
    subprocess.call(
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2022-02-07 12:16:06,067 DEBUG   HandlerThread:6854 [meta.py:_save_conda():89] save conda done
2022-02-07 12:16:06,067 DEBUG   HandlerThread:6854 [meta.py:probe():252] probe done
2022-02-07 12:16:06,461 DEBUG   SenderThread:6854 [sender.py:send():238] send: files
2022-02-07 12:16:06,462 INFO    SenderThread:6854 [sender.py:_save_file():960] saving file wandb-metadata.json with policy now
2022-02-07 12:16:06,493 DEBUG   HandlerThread:6854 [handler.py:handle_request():130] handle_request: stop_status
2022-02-07 12:16:06,503 DEBUG   SenderThread:6854 [sender.py:send_request():252] send_request: stop_status
2022-02-07 12:16:07,017 INFO    Thread-13 :6854 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220207_121603-2t3o8y1h/files/requirements.txt
2022-02-07 12:16:07,018 INFO    Thread-13 :6854 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220207_121603-2t3o8y1h/files/wandb-summary.json
2022-02-07 12:16:07,019 INFO    Thread-13 :6854 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220207_121603-2t3o8y1h/files/output.log
2022-02-07 12:16:07,020 INFO    Thread-13 :6854 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220207_121603-2t3o8y1h/files/conda-environment.yaml
2022-02-07 12:16:07,020 INFO    Thread-13 :6854 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220207_121603-2t3o8y1h/files/wandb-metadata.json
2022-02-07 12:16:07,259 INFO    Thread-16 :6854 [upload_job.py:push():137] Uploaded file /tmp/tmplyazdnj2wandb/242h1cby-wandb-metadata.json
2022-02-07 12:16:09,006 INFO    Thread-13 :6854 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sohui/code/DTC/code/wandb/run-20220207_121603-2t3o8y1h/files/output.log
2022-02-07 12:16:13,010 INFO    Thread-13 :6854 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sohui/code/DTC/code/wandb/run-20220207_121603-2t3o8y1h/files/output.log
2022-02-07 12:16:21,850 DEBUG   HandlerThread:6854 [handler.py:handle_request():130] handle_request: stop_status
2022-02-07 12:16:21,851 DEBUG   SenderThread:6854 [sender.py:send_request():252] send_request: stop_status
2022-02-07 12:16:37,174 DEBUG   HandlerThread:6854 [handler.py:handle_request():130] handle_request: stop_status
2022-02-07 12:16:37,175 DEBUG   SenderThread:6854 [sender.py:send_request():252] send_request: stop_status
2022-02-07 12:16:38,317 DEBUG   SenderThread:6854 [sender.py:send():238] send: stats
2022-02-07 12:16:46,123 WARNING MainThread:6854 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-02-07 12:16:49,056 INFO    Thread-13 :6854 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sohui/code/DTC/code/wandb/run-20220207_121603-2t3o8y1h/files/output.log
