2022-02-18 08:53:02,755 INFO    MainThread:32220 [internal.py:wandb_internal():87] W&B internal server running at pid: 32220, started at: 2022-02-18 08:53:02.754484
2022-02-18 08:53:02,766 DEBUG   HandlerThread:32220 [handler.py:handle_request():130] handle_request: check_version
2022-02-18 08:53:02,767 INFO    WriterThread:32220 [datastore.py:open_for_write():77] open: /home/sohui/code/DTC/code/wandb/run-20220218_085300-tyq1qa2s/run-tyq1qa2s.wandb
2022-02-18 08:53:02,780 DEBUG   SenderThread:32220 [sender.py:send():238] send: header
2022-02-18 08:53:02,780 DEBUG   SenderThread:32220 [sender.py:send_request():252] send_request: check_version
2022-02-18 08:53:02,954 DEBUG   SenderThread:32220 [sender.py:send():238] send: run
2022-02-18 08:53:03,272 INFO    SenderThread:32220 [dir_watcher.py:__init__():169] watching files in: /home/sohui/code/DTC/code/wandb/run-20220218_085300-tyq1qa2s/files
2022-02-18 08:53:03,273 INFO    SenderThread:32220 [sender.py:_start_run_threads():825] run started: tyq1qa2s with start time 1645174381
2022-02-18 08:53:03,273 DEBUG   SenderThread:32220 [sender.py:send():238] send: summary
2022-02-18 08:53:03,274 INFO    SenderThread:32220 [sender.py:_save_file():960] saving file wandb-summary.json with policy end
2022-02-18 08:53:03,279 DEBUG   HandlerThread:32220 [handler.py:handle_request():130] handle_request: run_start
2022-02-18 08:53:03,294 DEBUG   HandlerThread:32220 [meta.py:__init__():40] meta init
2022-02-18 08:53:03,295 DEBUG   HandlerThread:32220 [meta.py:__init__():54] meta init done
2022-02-18 08:53:03,295 DEBUG   HandlerThread:32220 [meta.py:probe():214] probe
2022-02-18 08:53:03,305 DEBUG   HandlerThread:32220 [git.py:repo():33] git repository is invalid
2022-02-18 08:53:03,305 DEBUG   HandlerThread:32220 [meta.py:_save_pip():58] save pip
2022-02-18 08:53:03,311 DEBUG   HandlerThread:32220 [meta.py:_save_pip():72] save pip done
2022-02-18 08:53:03,312 DEBUG   HandlerThread:32220 [meta.py:_save_conda():79] save conda
2022-02-18 08:53:03,321 ERROR   HandlerThread:32220 [meta.py:_save_conda():88] Error saving conda packages
Traceback (most recent call last):
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/site-packages/wandb/sdk/internal/meta.py", line 84, in _save_conda
    subprocess.call(
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2022-02-18 08:53:03,325 DEBUG   HandlerThread:32220 [meta.py:_save_conda():89] save conda done
2022-02-18 08:53:03,326 DEBUG   HandlerThread:32220 [meta.py:probe():252] probe done
2022-02-18 08:53:03,655 WARNING MainThread:32220 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-02-18 08:53:03,668 DEBUG   SenderThread:32220 [sender.py:send():238] send: files
2022-02-18 08:53:03,669 INFO    SenderThread:32220 [sender.py:_save_file():960] saving file wandb-metadata.json with policy now
2022-02-18 08:53:04,289 INFO    Thread-13 :32220 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220218_085300-tyq1qa2s/files/wandb-metadata.json
2022-02-18 08:53:04,290 INFO    Thread-13 :32220 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220218_085300-tyq1qa2s/files/wandb-summary.json
2022-02-18 08:53:04,290 INFO    Thread-13 :32220 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220218_085300-tyq1qa2s/files/requirements.txt
2022-02-18 08:53:04,291 INFO    Thread-13 :32220 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220218_085300-tyq1qa2s/files/conda-environment.yaml
2022-02-18 08:53:04,341 INFO    Thread-16 :32220 [upload_job.py:push():137] Uploaded file /tmp/tmp43mpnsd5wandb/k2ffiumz-wandb-metadata.json
