2022-02-18 08:53:00,518 INFO    MainThread:32109 [wandb_setup.py:_flush():71] setting env: {}
2022-02-18 08:53:00,518 INFO    MainThread:32109 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-18 08:53:00,518 INFO    MainThread:32109 [wandb_init.py:_log_setup():371] Logging user logs to /home/sohui/code/DTC/code/wandb/run-20220218_085300-tyq1qa2s/logs/debug.log
2022-02-18 08:53:00,519 INFO    MainThread:32109 [wandb_init.py:_log_setup():372] Logging internal logs to /home/sohui/code/DTC/code/wandb/run-20220218_085300-tyq1qa2s/logs/debug-internal.log
2022-02-18 08:53:00,519 INFO    MainThread:32109 [wandb_init.py:init():404] calling init triggers
2022-02-18 08:53:00,519 INFO    MainThread:32109 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'mdoel': 'DTC', 'server': 57, 'image size': '112,112,80'}
2022-02-18 08:53:00,520 INFO    MainThread:32109 [wandb_init.py:init():449] starting backend
2022-02-18 08:53:00,520 INFO    MainThread:32109 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-18 08:53:00,707 INFO    MainThread:32109 [backend.py:ensure_launched():199] starting backend process...
2022-02-18 08:53:01,333 INFO    MainThread:32109 [backend.py:ensure_launched():204] started backend process with pid: 32220
2022-02-18 08:53:01,338 INFO    MainThread:32109 [wandb_init.py:init():458] backend started and connected
2022-02-18 08:53:01,350 INFO    MainThread:32109 [wandb_init.py:init():519] updated telemetry
2022-02-18 08:53:01,354 INFO    MainThread:32109 [wandb_init.py:init():549] communicating current version
2022-02-18 08:53:02,948 INFO    MainThread:32109 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-18 08:53:02,950 INFO    MainThread:32109 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2022-02-18 08:53:03,278 INFO    MainThread:32109 [wandb_init.py:init():592] starting run threads in backend
2022-02-18 08:53:03,655 WARNING MainThread:32109 [wandb_init.py:init():938] interrupted
Traceback (most recent call last):
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 917, in init
    run = wi.init()
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 597, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 216, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 446, in _communicate_run_start
    result = self._communicate(rec)
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 32, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
